apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/gurnben/olm-operator-konflux-sample?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch == "main" && 
      (".tekton/multi-arch-build-pipeline.yaml".pathChanged() || 
      ".tekton/olm-operator-konflux-sample-gatekeeper-operator-pull-request.yaml".pathChanged() || 
      ".tekton/olm-operator-konflux-sample-gatekeeper-operator-push.yaml".pathChanged() || 
      "Containerfile.gatekeeper-operator".pathChanged() ||
      "gatekeeper-operator".pathChanged())
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: gatekeeper-example-application
    appstudio.openshift.io/component: olm-operator-konflux-sample-gatekeeper-operator
    pipelines.appstudio.openshift.io/type: build
  name: olm-operator-konflux-sample-gatekeeper-operator-on-push
  namespace: gurney-buchanan-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/gurney-buchanan-tenant/gatekeeper-example-application/olm-operator-konflux-sample-gatekeeper-operator:{{revision}}
  - name: dockerfile
    value: Containerfile.gatekeeper-operator
  pipelineRef:
    name: multi-arch-build-pipeline
  taskRunTemplate: {}
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
